[02/Aug/2016 18:25:44] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:44] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 18:25:48] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:53] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:25:59] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:04] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:07] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:08] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:08] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:09] ERROR [django.request:231] Internal Server Error: /sequencelistings/add_sequencelisting/
Traceback (most recent call last):
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/views.py", line 78, in add_sequencelisting
    inventorNameLatin = request.POST.get('inventorNameLatin'),
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 919, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 877, in as_sql
    for obj in self.query.objs
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 627, in get_db_prep_save
    prepared=False)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1176, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1171, in get_prep_value
    return self.to_python(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1141, in to_python
    params={'value': value},
ValidationError: [u"'' value has an invalid date format. It must be in YYYY-MM-DD format."]
[02/Aug/2016 18:26:09] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:26:09] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:26:19] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:26] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:29] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:30] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:30] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:37] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:37] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:41] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:48] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:49] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:26:49] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:43] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:43] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 18:29:46] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:49] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:50] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:56] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:29:59] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:00] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:00] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:01] ERROR [django.request:231] Internal Server Error: /sequencelistings/add_sequencelisting/
Traceback (most recent call last):
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/views.py", line 78, in add_sequencelisting
    inventorNameLatin = request.POST.get('inventorNameLatin'),
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 919, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 877, in as_sql
    for obj in self.query.objs
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 627, in get_db_prep_save
    prepared=False)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1176, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1171, in get_prep_value
    return self.to_python(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1141, in to_python
    params={'value': value},
ValidationError: [u"'' value has an invalid date format. It must be in YYYY-MM-DD format."]
[02/Aug/2016 18:30:01] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:30:01] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:30:11] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:18] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:21] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:22] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:23] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:24] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:24] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:28] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:35] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:36] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:30:36] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:37] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:37] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 18:36:40] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:44] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:45] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:46] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:47] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:47] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:54] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:55] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:56] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:36:57] ERROR [django.request:231] Internal Server Error: /sequencelistings/add_sequencelisting/
Traceback (most recent call last):
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/views.py", line 78, in add_sequencelisting
    inventorNameLatin = request.POST.get('inventorNameLatin'),
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 919, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 877, in as_sql
    for obj in self.query.objs
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 627, in get_db_prep_save
    prepared=False)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1176, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1171, in get_prep_value
    return self.to_python(value)
  File "/Users/ad/pyton/projects/new_auth/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1141, in to_python
    params={'value': value},
ValidationError: [u"'' value has an invalid date format. It must be in YYYY-MM-DD format."]
[02/Aug/2016 18:36:57] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:36:57] WARNING [django.request:143] Not Found: /favicon.ico
[02/Aug/2016 18:37:07] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:13] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:17] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:18] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:18] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:19] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:19] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:23] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:30] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:31] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:37:31] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:03] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:03] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 18:40:07] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:10] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:11] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:11] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:13] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:13] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:17] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:20] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:21] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:21] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:22] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:33] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:36] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:40] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:41] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:41] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:42] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:42] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:46] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:53] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:54] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:40:54] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:08] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:08] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 18:41:13] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:16] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:17] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:17] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:18] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:19] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:22] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:26] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:32] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:32] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:34] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:44] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:48] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:52] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:53] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:54] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:41:57] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:42:04] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:42:05] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:42:06] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: ab(c.
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: a(b9c.
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:168] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test6.xml
Opening and ending tag mismatch: ApplicantNamey line 21 and ApplicantName, line 23, column 34
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test7.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantsName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceTotalQuantity SequenceData SequenceData )
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceData SequenceData )
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:151] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test4.xml
Opening and ending tag mismatch: ApplicantNamex line 20 and ApplicantName, line 22, column 34
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'INSDFeature_key': [facet 'enumeration'] The value 'SOURCxE' is not an element of the set {'allele', 'attenuator', 'C_region', 'CAAT_signal', 'CDS', 'conflict', 'D-loop', 'D_segment', 'enhancer', 'exon', 'GC_signal', 'gene', 'iDNA', 'intron', 'J_segment', 'LTR', 'mat_peptide', 'misc_binding', 'misc_difference', 'misc_feature', 'misc_recomb', 'misc_RNA', 'misc_signal', 'misc_structure', 'modified_base', 'mRNA', 'mutation', 'N_region', 'old_sequence', 'polyA_signal', 'polyA_site', 'precursor_RNA', 'prim_transcript', 'primer_bind', 'promoter', 'protein_bind', 'RBS', 'repeat_region', 'repeat_unit', 'rep_origin', 'rRNA', 'S_region', 'satellite', 'scRNA', 'sig_peptide', 'snRNA', 'source', 'stem_loop', 'STS', 'TATA_signal', 'terminator', 'transit_peptide', 'tRNA', 'unsure', 'V_region', 'V_segment', 'variation', '3'clip', '3'UTR', '5'clip', '5'UTR', '-10_signal', '-35_signal', 'ACT_SITE', 'BINDING', 'CA_BIND', 'CARBOHYD', 'CHAIN', 'COILED', 'COMPBIAS', 'CONFLICT', 'CROSSLNK', 'DISULFID', 'DNA_BIND', 'DOMAIN', 'HELIX', 'INIT_MET', 'INTRAMEM', 'LIPID', 'METAL', 'MOD_RES', 'MOTIF', 'MUTAGEN', 'NON_STD', 'NON_TER', 'NP_BIND', 'PEPTIDE', 'PROPEP', 'REGION', 'REPEAT', 'SIGNAL', 'SITE', 'SOURCE', 'STRAND', 'TOPO_DOM', 'TRANSMEM', 'TRANSIT', 'TURN', 'UNSURE', 'VARIANT', 'VAR_SEQ', 'ZN_FING'}.
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'INSDFeature_key': 'SOURCxE' is not a valid value of the atomic type 'featureKeyValue'.
[02/Aug/2016 18:42:11] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml:42:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'SequenceData': This element is not expected. Expected is ( EarliestPriorityApplicationIdentification ).
[02/Aug/2016 19:15:40] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:40] WARNING [django.request:143] Not Found: /static/images/rango.jpg
[02/Aug/2016 19:15:45] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:48] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:49] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:49] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:51] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:55] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:58] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:59] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:15:59] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:00] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:10] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:14] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:17] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:18] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:19] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:20] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:20] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:24] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:31] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:32] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:37] WARNING [django.request:143] Not Found: /static/sequencelistings/output/resources/style.css
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: ab(c.
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: a(b9c.
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:168] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test6.xml
Opening and ending tag mismatch: ApplicantNamey line 21 and ApplicantName, line 23, column 34
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test7.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantsName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceTotalQuantity SequenceData SequenceData )
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceData SequenceData )
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:151] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test4.xml
Opening and ending tag mismatch: ApplicantNamex line 20 and ApplicantName, line 22, column 34
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'INSDFeature_key': [facet 'enumeration'] The value 'SOURCxE' is not an element of the set {'allele', 'attenuator', 'C_region', 'CAAT_signal', 'CDS', 'conflict', 'D-loop', 'D_segment', 'enhancer', 'exon', 'GC_signal', 'gene', 'iDNA', 'intron', 'J_segment', 'LTR', 'mat_peptide', 'misc_binding', 'misc_difference', 'misc_feature', 'misc_recomb', 'misc_RNA', 'misc_signal', 'misc_structure', 'modified_base', 'mRNA', 'mutation', 'N_region', 'old_sequence', 'polyA_signal', 'polyA_site', 'precursor_RNA', 'prim_transcript', 'primer_bind', 'promoter', 'protein_bind', 'RBS', 'repeat_region', 'repeat_unit', 'rep_origin', 'rRNA', 'S_region', 'satellite', 'scRNA', 'sig_peptide', 'snRNA', 'source', 'stem_loop', 'STS', 'TATA_signal', 'terminator', 'transit_peptide', 'tRNA', 'unsure', 'V_region', 'V_segment', 'variation', '3'clip', '3'UTR', '5'clip', '5'UTR', '-10_signal', '-35_signal', 'ACT_SITE', 'BINDING', 'CA_BIND', 'CARBOHYD', 'CHAIN', 'COILED', 'COMPBIAS', 'CONFLICT', 'CROSSLNK', 'DISULFID', 'DNA_BIND', 'DOMAIN', 'HELIX', 'INIT_MET', 'INTRAMEM', 'LIPID', 'METAL', 'MOD_RES', 'MOTIF', 'MUTAGEN', 'NON_STD', 'NON_TER', 'NP_BIND', 'PEPTIDE', 'PROPEP', 'REGION', 'REPEAT', 'SIGNAL', 'SITE', 'SOURCE', 'STRAND', 'TOPO_DOM', 'TRANSMEM', 'TRANSIT', 'TURN', 'UNSURE', 'VARIANT', 'VAR_SEQ', 'ZN_FING'}.
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'INSDFeature_key': 'SOURCxE' is not a valid value of the atomic type 'featureKeyValue'.
[02/Aug/2016 19:16:43] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml:42:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'SequenceData': This element is not expected. Expected is ( EarliestPriorityApplicationIdentification ).
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: ab(c.
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: a(b9c.
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:168] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test6.xml
Opening and ending tag mismatch: ApplicantNamey line 21 and ApplicantName, line 23, column 34
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test7.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantsName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceTotalQuantity SequenceData SequenceData )
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceData SequenceData )
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:151] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test4.xml
Opening and ending tag mismatch: ApplicantNamex line 20 and ApplicantName, line 22, column 34
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'INSDFeature_key': [facet 'enumeration'] The value 'SOURCxE' is not an element of the set {'allele', 'attenuator', 'C_region', 'CAAT_signal', 'CDS', 'conflict', 'D-loop', 'D_segment', 'enhancer', 'exon', 'GC_signal', 'gene', 'iDNA', 'intron', 'J_segment', 'LTR', 'mat_peptide', 'misc_binding', 'misc_difference', 'misc_feature', 'misc_recomb', 'misc_RNA', 'misc_signal', 'misc_structure', 'modified_base', 'mRNA', 'mutation', 'N_region', 'old_sequence', 'polyA_signal', 'polyA_site', 'precursor_RNA', 'prim_transcript', 'primer_bind', 'promoter', 'protein_bind', 'RBS', 'repeat_region', 'repeat_unit', 'rep_origin', 'rRNA', 'S_region', 'satellite', 'scRNA', 'sig_peptide', 'snRNA', 'source', 'stem_loop', 'STS', 'TATA_signal', 'terminator', 'transit_peptide', 'tRNA', 'unsure', 'V_region', 'V_segment', 'variation', '3'clip', '3'UTR', '5'clip', '5'UTR', '-10_signal', '-35_signal', 'ACT_SITE', 'BINDING', 'CA_BIND', 'CARBOHYD', 'CHAIN', 'COILED', 'COMPBIAS', 'CONFLICT', 'CROSSLNK', 'DISULFID', 'DNA_BIND', 'DOMAIN', 'HELIX', 'INIT_MET', 'INTRAMEM', 'LIPID', 'METAL', 'MOD_RES', 'MOTIF', 'MUTAGEN', 'NON_STD', 'NON_TER', 'NP_BIND', 'PEPTIDE', 'PROPEP', 'REGION', 'REPEAT', 'SIGNAL', 'SITE', 'SOURCE', 'STRAND', 'TOPO_DOM', 'TRANSMEM', 'TRANSIT', 'TURN', 'UNSURE', 'VARIANT', 'VAR_SEQ', 'ZN_FING'}.
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'INSDFeature_key': 'SOURCxE' is not a valid value of the atomic type 'featureKeyValue'.
[02/Aug/2016 19:20:23] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml:42:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'SequenceData': This element is not expected. Expected is ( EarliestPriorityApplicationIdentification ).
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: ab(c.
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: a(b9c.
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:168] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test6.xml
Opening and ending tag mismatch: ApplicantNamey line 21 and ApplicantName, line 23, column 34
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test7.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantsName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceTotalQuantity SequenceData SequenceData )
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceData SequenceData )
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:151] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test4.xml
Opening and ending tag mismatch: ApplicantNamex line 20 and ApplicantName, line 22, column 34
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'INSDFeature_key': [facet 'enumeration'] The value 'SOURCxE' is not an element of the set {'allele', 'attenuator', 'C_region', 'CAAT_signal', 'CDS', 'conflict', 'D-loop', 'D_segment', 'enhancer', 'exon', 'GC_signal', 'gene', 'iDNA', 'intron', 'J_segment', 'LTR', 'mat_peptide', 'misc_binding', 'misc_difference', 'misc_feature', 'misc_recomb', 'misc_RNA', 'misc_signal', 'misc_structure', 'modified_base', 'mRNA', 'mutation', 'N_region', 'old_sequence', 'polyA_signal', 'polyA_site', 'precursor_RNA', 'prim_transcript', 'primer_bind', 'promoter', 'protein_bind', 'RBS', 'repeat_region', 'repeat_unit', 'rep_origin', 'rRNA', 'S_region', 'satellite', 'scRNA', 'sig_peptide', 'snRNA', 'source', 'stem_loop', 'STS', 'TATA_signal', 'terminator', 'transit_peptide', 'tRNA', 'unsure', 'V_region', 'V_segment', 'variation', '3'clip', '3'UTR', '5'clip', '5'UTR', '-10_signal', '-35_signal', 'ACT_SITE', 'BINDING', 'CA_BIND', 'CARBOHYD', 'CHAIN', 'COILED', 'COMPBIAS', 'CONFLICT', 'CROSSLNK', 'DISULFID', 'DNA_BIND', 'DOMAIN', 'HELIX', 'INIT_MET', 'INTRAMEM', 'LIPID', 'METAL', 'MOD_RES', 'MOTIF', 'MUTAGEN', 'NON_STD', 'NON_TER', 'NP_BIND', 'PEPTIDE', 'PROPEP', 'REGION', 'REPEAT', 'SIGNAL', 'SITE', 'SOURCE', 'STRAND', 'TOPO_DOM', 'TRANSMEM', 'TRANSIT', 'TURN', 'UNSURE', 'VARIANT', 'VAR_SEQ', 'ZN_FING'}.
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'INSDFeature_key': 'SOURCxE' is not a valid value of the atomic type 'featureKeyValue'.
[02/Aug/2016 19:21:45] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml:42:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'SequenceData': This element is not expected. Expected is ( EarliestPriorityApplicationIdentification ).
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: ab(c.
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:123] The residues string contains "(" but does not match formula pattern. Residues: a(b9c.
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:168] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test6.xml
Opening and ending tag mismatch: ApplicantNamey line 21 and ApplicantName, line 23, column 34
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test7.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantsName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceTotalQuantity SequenceData SequenceData )
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:166] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml
<string>:8:0:ERROR:VALID:DTD_CONTENT_MODEL: Element ST26SequenceListing content does not follow the DTD, expecting ((ApplicantFileReference | (ApplicationIdentification , ApplicantFileReference?)) , EarliestPriorityApplicationIdentification? , (ApplicantName , ApplicantNameLatin?)? , (InventorName , InventorNameLatin?)? , InventionTitle+ , SequenceTotalQuantity , SequenceData+), got (ApplicationIdentification ApplicantFileReference EarliestPriorityApplicationIdentification ApplicantName ApplicantNameLatin InventorName InventorNameLatin InventionTitle InventionTitle SequenceData SequenceData )
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:151] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test4.xml
Opening and ending tag mismatch: ApplicantNamex line 20 and ApplicantName, line 22, column 34
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 'INSDFeature_key': [facet 'enumeration'] The value 'SOURCxE' is not an element of the set {'allele', 'attenuator', 'C_region', 'CAAT_signal', 'CDS', 'conflict', 'D-loop', 'D_segment', 'enhancer', 'exon', 'GC_signal', 'gene', 'iDNA', 'intron', 'J_segment', 'LTR', 'mat_peptide', 'misc_binding', 'misc_difference', 'misc_feature', 'misc_recomb', 'misc_RNA', 'misc_signal', 'misc_structure', 'modified_base', 'mRNA', 'mutation', 'N_region', 'old_sequence', 'polyA_signal', 'polyA_site', 'precursor_RNA', 'prim_transcript', 'primer_bind', 'promoter', 'protein_bind', 'RBS', 'repeat_region', 'repeat_unit', 'rep_origin', 'rRNA', 'S_region', 'satellite', 'scRNA', 'sig_peptide', 'snRNA', 'source', 'stem_loop', 'STS', 'TATA_signal', 'terminator', 'transit_peptide', 'tRNA', 'unsure', 'V_region', 'V_segment', 'variation', '3'clip', '3'UTR', '5'clip', '5'UTR', '-10_signal', '-35_signal', 'ACT_SITE', 'BINDING', 'CA_BIND', 'CARBOHYD', 'CHAIN', 'COILED', 'COMPBIAS', 'CONFLICT', 'CROSSLNK', 'DISULFID', 'DNA_BIND', 'DOMAIN', 'HELIX', 'INIT_MET', 'INTRAMEM', 'LIPID', 'METAL', 'MOD_RES', 'MOTIF', 'MUTAGEN', 'NON_STD', 'NON_TER', 'NP_BIND', 'PEPTIDE', 'PROPEP', 'REGION', 'REPEAT', 'SIGNAL', 'SITE', 'SOURCE', 'STRAND', 'TOPO_DOM', 'TRANSMEM', 'TRANSIT', 'TURN', 'UNSURE', 'VARIANT', 'VAR_SEQ', 'ZN_FING'}.
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test5.xml:103:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'INSDFeature_key': 'SOURCxE' is not a valid value of the atomic type 'featureKeyValue'.
[02/Aug/2016 19:26:29] ERROR [sequencelistings.util:149] 
/Users/ad/pyton/projects/st26proto/authoringtool/sequencelistings/testData/test8.xml:42:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'SequenceData': This element is not expected. Expected is ( EarliestPriorityApplicationIdentification ).
